# Generated by Django 5.2.1 on 2025-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
